### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by ydorje** [a-s-g93/neo4j-runway#106]
How do fix this error from this step "gdm.create_initial_model()"

 TypeError: issubclass() arg 1 must be a class    

The error comes from:

File c:\Users\cccc\Anaconda3\envs\neo4j-env\Lib\site-packages\instructor\function_calls.py:468, in openai_schema_helper(cls)
  if origin is Union:
      return Union[tuple(openai_schema_helper(arg) for arg in cls.__args__)]
 if issubclass(cls, (str, int, bool, float, bytes, Enum)):
     return cls
 if isinstance(cls, type) and issubclass(cls, BaseModel):

**Comment by a-s-g93** [comment]
This is addressed here: https://github.com/a-s-g93/neo4j-runway/issues/104
